version: '3.8'

services:
  router:
    image: ghcr.io/wundergraph/cosmo/router:latest
    environment:
      LISTEN_ADDR: 0.0.0.0:3002
      LOG_LEVEL: info
    volumes:
      - type: bind
        source: ./router.config.yaml
        target: /config.yaml
    ports:
      - "3002:3002"


  employees:
    image: node:20
    working_dir: /app
    command: node server.js
    volumes:
      - ./subgraph:/app
    ports:
      - "4001:4001"
